name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker://florianpiesche/moonlight-nx-build:latest
      env:
        # As pkgbuild needs to run unprivileged, this defines the user it will be run as
        LIBCURL_BUILD_USER: build

    steps:

    - name: Check out repository
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Run build
      run: ./build.sh

    - name: Upload moonlight.nro
      uses: actions/upload-artifact@master
      with:
        name: moonlight
        path: moonlight.nro
