name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker://florianpiesche/moonlight-nx-build:latest

    steps:

    - name: Check out repository
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Update pacman packages
      run: dkp-pacman -Suy --noconfirm

    - name: Run build
      run: ./build.sh

    - name: Upload moonlight.nro
      uses: actions/upload-artifact@master
      with:
        name: moonlight
        path: moonlight.nro
